# Generated by Django 3.2.15 on 2024-10-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20241016_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(default='6+', max_length=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='age_restriction',
            field=models.CharField(default='6+', max_length=5),
        ),
    ]
