# Generated by Django 3.2.15 on 2024-10-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_moviepremiersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepremiersession',
            name='available_tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviepremiersession',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='moviepremiersession',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
