name: Docker Image CI

on:
  push:
    branches: [ "Back-DEV" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-docker Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/marsvest/vl_backend:latest

    - name: push image to GitHub Container Registry
      run: docker push ghcr.io/marsvest/vl_backend