name: Docker Image CI

on:
  push:
    branches: [ "Back-DEV" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vl_backend:$(date +%s)