name: Docker Image CI

on:
  push:
    branches: [ "Back-DEV" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Github Login
        uses: docker/login-action@v3
        with:

          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v4
      - name: Build and Push the Docker image
        run: |
                docker build . --file Dockerfile --tag ghcr.io/marsvest/vl_backend:latest
                docker push ghcr.io/marsvest/vl_backend:latest


